version: "3.7"

services:
  database_medcloud:
    image: postgres
    container_name: database_medcloud
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: medcloud
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
    - database_medcloud
    depends_on:
    - database_medcloud
    


volumes:
  pgdata:
    driver: local